version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - 8009:8000
    volumes:
      - ./backend:/usr/src/app
    restart: always
    ipc: host
    environment:
      - DB_HOST=localhost
      - DB_NAME=coin
      - DB_USER=root
      - DB_PW=1234
      - EXPORT_HOST=localhost
      - EXPORT_PORT=89
      - TZ=Asia/Seoul
    # command: tail -F /dev/null
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - 3009:3000
    volumes:
      - ./frontend:/usr/src/app
    restart: always
    ipc: host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - TZ=Asia/Seoul
    # command: npm start
    command: npm run dev

  revers_proxy:
    build: ./nginx
    ports:
      - 89:80
    depends_on:
      - backend
      - frontend
    restart: always
