version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - 8009:8000
    volumes:
      - ./backend:/usr/src/app
    restart: always
    ipc: host
    environment:
      - DB_HOST=localhost
      - DB_NAME=coin
      - DB_USER=root
      - DB_PW=dmsal369
      - EXPORT_HOST=localhost
      - EXPORT_PORT=89
      - TZ=Asia/Seoul

    command: python manage.py runserver 0.0.0.0:8000

  revers_proxy:
    build: ./nginx
    ports:
      - 89:80
    depends_on:
      - backend
    restart: always
